/// <reference types="@cloudflare/workers-types" />

/**
 * Custom Cloudflare Worker entrypoint (Phase D — D1).
 *
 * The OpenNext-generated `.open-next/worker.js` exports ONLY a `fetch` handler
 * (see node_modules/@opennextjs/cloudflare custom-worker how-to). To run the
 * poller on a Cron Trigger we need a `scheduled(event, env, ctx)` handler too,
 * so this file wraps the generated worker: a DEFAULT export object carrying its
 * `fetch` verbatim (Next.js request handling is unchanged) plus `scheduled`, and
 * NAMED re-exports of its Durable Object classes (the OpenNext cache queue + tag
 * cache). The default-export shape is required for the deployed static-assets
 * router to attach — see the export-shape note below.
 *
 * `wrangler.jsonc` `main` points here instead of at `.open-next/worker.js`. Both
 * imported modules are BUILD ARTIFACTS regenerated by every
 * `opennextjs-cloudflare build` and do not exist in a clean tree (`.open-next/`
 * is gitignored), so this file is EXCLUDED from `tsc --noEmit` (tsconfig
 * `exclude`) — it is a Cloudflare Worker entrypoint, type-checked by the
 * wrangler/esbuild build (`opennextjs-cloudflare build`), not by the app's
 * Node typecheck. The `.open-next/*` imports therefore need no suppression
 * directive.
 *
 * ── Why the context dance in `scheduled` ─────────────────────────────────────
 * The whole ingest layer (poll -> live-window -> lease -> targets) reaches
 * D1/KV through the request-scoped `@/db` proxy and `getEnv()`, both of which
 * read OpenNext's AsyncLocalStorage-backed Cloudflare context (see
 * lib/runtime/workers-env.ts). On the `fetch` path OpenNext establishes that
 * context for us. A `scheduled` invocation has no incoming `Request`, so we
 * establish the SAME context ourselves via OpenNext's
 * `runWithCloudflareRequestContext` (exported from the generated init module)
 * with a synthetic Request — after which `db`/`getEnv()` resolve `env.DB` and
 * `env.POLLER_KV` exactly as they do for `/api/poll`, with zero ingest-layer
 * rewiring.
 *
 * ── Why a DEFAULT export, not named `fetch`/`scheduled` ──────────────────────
 * The Worker MUST expose its handlers as a `export default { fetch, scheduled }`
 * object, exactly as OpenNext's custom-worker how-to prescribes
 * (https://opennext.js.org/cloudflare/howtos/custom-worker). This is not
 * cosmetic: on a Worker-with-Assets deploy, Cloudflare's static-assets routing
 * layer attaches to the Worker's DEFAULT export. With only NAMED exports
 * (`export const fetch` / `export { scheduled }`) the deployed asset router does
 * not hand asset-miss navigations and `/api/*` to the Worker — the edge answers
 * a bare 404 for every path and the Worker is never invoked (confirmed: the 404
 * carried only Cloudflare edge headers, no OpenNext/Next headers). `wrangler dev`
 * / `opennextjs-cloudflare preview` run on Miniflare, which is lenient about the
 * export shape, so preview served correctly and masked the bug. The Durable
 * Object classes stay NAMED exports (Cloudflare binds DOs by class name).
 */

import { runDispatcherTick } from "@/lib/ingest/poll";
import type { WorkerEnv } from "@/lib/runtime/workers-env";
import { runWithCloudflareRequestContext } from "./.open-next/cloudflare/init.js";
import { default as openNextHandler } from "./.open-next/worker.js";

/**
 * Cron Trigger entrypoint. Runs one bounded dispatcher tick (the same
 * `runDispatcherTick` path `/api/poll` uses with no `mode` param): a KV-gated
 * live tick, then an archive tick only during an idle slot. Bounded work per
 * tick and per-fetch AbortSignals are preserved inside the tick itself.
 *
 * `ctx.waitUntil` keeps the invocation alive for the async tick. Errors are
 * swallowed (logged) so a single bad tick never fails the schedule; the next
 * minute retries.
 */
async function scheduled(
  _event: ScheduledController,
  env: WorkerEnv,
  ctx: ExecutionContext,
): Promise<void> {
  // Synthetic request: `runWithCloudflareRequestContext` only reads `url` and
  // `cf` off it to seed the context; the poller never touches the request.
  const syntheticRequest = new Request("https://cron.internal/scheduled");
  const work = runWithCloudflareRequestContext(
    syntheticRequest,
    env,
    ctx,
    async () => {
      try {
        await runDispatcherTick();
      } catch (error) {
        console.error("[cron] dispatcher tick failed", error);
      }
    },
  );
  ctx.waitUntil(work);
  await work;
}

// The Worker entrypoint. `fetch` is OpenNext's generated handler verbatim
// (Next.js keeps handling every HTTP request — pages, /api/*, assets); `scheduled`
// is the Phase D cron. Exposed as a DEFAULT export so the deployed static-assets
// router attaches to it (see the export-shape note above).
export default {
  fetch: openNextHandler.fetch,
  scheduled,
} satisfies ExportedHandler<WorkerEnv>;

// Re-export the OpenNext Durable Objects (cache queue + sharded tag cache +
// bucket cache purge) as NAMED exports. Required because the generated worker
// declares them and wrangler binds them by class name; omitting the re-export
// breaks the deploy.
export {
  BucketCachePurge,
  DOQueueHandler,
  DOShardedTagCache,
} from "./.open-next/worker.js";
