/// <reference types="@cloudflare/workers-types" />

/**
 * Custom Cloudflare Worker entrypoint (Phase D — D1).
 *
 * The OpenNext-generated `.open-next/worker.js` exports ONLY a `fetch` handler
 * (see node_modules/@opennextjs/cloudflare custom-worker how-to). To run the
 * poller on a Cron Trigger we need a `scheduled(event, env, ctx)` handler too,
 * so this file wraps the generated worker: it re-exports its `fetch` verbatim
 * (Next.js request handling is unchanged) and its Durable Object classes (the
 * OpenNext cache queue + tag cache), and adds `scheduled`.
 *
 * `wrangler.jsonc` `main` points here instead of at `.open-next/worker.js`. Both
 * imported modules are BUILD ARTIFACTS regenerated by every
 * `opennextjs-cloudflare build` and do not exist in a clean tree (`.open-next/`
 * is gitignored), so this file is EXCLUDED from `tsc --noEmit` (tsconfig
 * `exclude`) — it is a Cloudflare Worker entrypoint, type-checked by the
 * wrangler/esbuild build (`opennextjs-cloudflare build`), not by the app's
 * Node typecheck. The `.open-next/*` imports therefore need no suppression
 * directive.
 *
 * ── Why the context dance in `scheduled` ─────────────────────────────────────
 * The whole ingest layer (poll -> live-window -> lease -> targets) reaches
 * D1/KV through the request-scoped `@/db` proxy and `getEnv()`, both of which
 * read OpenNext's AsyncLocalStorage-backed Cloudflare context (see
 * lib/runtime/workers-env.ts). On the `fetch` path OpenNext establishes that
 * context for us. A `scheduled` invocation has no incoming `Request`, so we
 * establish the SAME context ourselves via OpenNext's
 * `runWithCloudflareRequestContext` (exported from the generated init module)
 * with a synthetic Request — after which `db`/`getEnv()` resolve `env.DB` and
 * `env.POLLER_KV` exactly as they do for `/api/poll`, with zero ingest-layer
 * rewiring.
 */

import { runDispatcherTick } from "@/lib/ingest/poll";
import type { WorkerEnv } from "@/lib/runtime/workers-env";
import { runWithCloudflareRequestContext } from "./.open-next/cloudflare/init.js";
import { default as openNextHandler } from "./.open-next/worker.js";

// Re-export the OpenNext fetch handler unchanged — Next.js keeps handling every
// HTTP request (pages, /api/*, assets) exactly as before.
export const fetch = openNextHandler.fetch as ExportedHandlerFetchHandler;

/**
 * Cron Trigger entrypoint. Runs one bounded dispatcher tick (the same
 * `runDispatcherTick` path `/api/poll` uses with no `mode` param): a KV-gated
 * live tick, then an archive tick only during an idle slot. Bounded work per
 * tick and per-fetch AbortSignals are preserved inside the tick itself.
 *
 * `ctx.waitUntil` keeps the invocation alive for the async tick. Errors are
 * swallowed (logged) so a single bad tick never fails the schedule; the next
 * minute retries.
 */
async function scheduled(
  _event: ScheduledController,
  env: WorkerEnv,
  ctx: ExecutionContext,
): Promise<void> {
  // Synthetic request: `runWithCloudflareRequestContext` only reads `url` and
  // `cf` off it to seed the context; the poller never touches the request.
  const syntheticRequest = new Request("https://cron.internal/scheduled");
  const work = runWithCloudflareRequestContext(
    syntheticRequest,
    env,
    ctx,
    async () => {
      try {
        await runDispatcherTick();
      } catch (error) {
        console.error("[cron] dispatcher tick failed", error);
      }
    },
  );
  ctx.waitUntil(work);
  await work;
}

// Re-export the OpenNext Durable Objects (cache queue + sharded tag cache +
// bucket cache purge). Required because the generated worker declares them and
// wrangler binds them; omitting the re-export breaks the deploy.
export {
  BucketCachePurge,
  DOQueueHandler,
  DOShardedTagCache,
} from "./.open-next/worker.js";
export { scheduled };
